networks:
  app-network:
    driver: bridge
services:
  mongo:
    image: mongo:4.0-xenial
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    networks:
      - app-network
  # redis:
  #   image: redis:alpine
  #   restart: always
  #   ports:
  #     - 6379:6379
  #   #environment:
  #     #ALLOW_EMPTY_PASSWORD: yes
  #   networks:
  #     - app-network
volumes:
  data:
